#!/bin/bash
#
# chkconfig: 35 90 12 description: flamescp daemon
#
# Get function from functions library
. /etc/init.d/functions
# Start the service MAT
start() {
        bash /flamescpd
        service httpd start >> /dev/null
        echo "flamescpd: Started daemon!"
}
# Restart the service MAT
stop() {
        screen -S mined -X quit
        screen -S stopd -X quit
        screen -S cpuprot -X quit
        screen -S sendcmd -X quit
        echo "flamescpd: Â Stopped daemons and killed all running servers."
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1 
        esac 
        exit 0 

